### PR TITLE
installation instructions: update formatting, add another tip

### PR DESCRIPTION
**Pull request by floer32**

### CODE REVIEW

**Comment by shawnlawson** [comment]
Gotta solve this localhost https issue so that it's easy to use.

**Comment by shawnlawson** [comment]
This may work
https://gist.github.com/dergachev/7028596

**Comment by hangtwenty** [comment]
@shawnlawson Ahh awesome, just saw these instructions.

**Comment by floer32** [comment]
@shawnlawson Oh awesome, that works actually. At least, it works in Chrome. (Seems like maybe Safari doesn't like the invalid certificate.) I'll update the instructions.

**Pull request merged**
